# 通过spring.application.name属性，我们可以指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问。
spring:
   application:
      name: micros_cloud_spring_eureka

server:
   port: 8001

eureka:
   instance:
      hostname: localhost
   client:
      register-with-eureka: false
      fetch-registry: false