# http://localhost:8889/configserver
server:
  contextPath: /configserver
  port: 8889

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
         git:
          # 配置中心配置文件的项目地址
          uri: https://github.com/yueny/config-center.git
          username: yueny
          password: liyu.521.

#eureka.client.serviceUrl.defaultZone=http://peer1:1001/eureka/,http://peer2:1002/eureka/
eureka:
  client:
     serviceUrl:
        defaultZone: http://localhost:8001/eureka/