server:
  port: 8000

spring:
  application:
    name: config-server
  cloud:
    name: config-server
    config:
      server:
         git:
          # 配置中心配置地址
          uri: https://github.com/yueny/pra/tree/master/micros/cloud/config-center
          username: yueny
          password: liyu.521.

#eureka.client.serviceUrl.defaultZone=http://peer1:1001/eureka/,http://peer2:1002/eureka/
eureka:
  client:
     serviceUrl:
        defaultZone: http://localhost:8001/eureka/