server:
   port: 8000
spring: 
   aop: 
      proxy-target-class: true
      auto: true

app:
   system:
      code: cas_client

# url/shutdown
endpoints:
   shutdown:
      enabled: true

cas: 
   client:
      system: demo
